### ISSUE TITLE
Issue with live logs in CapRover console

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#366]
Thank you for implementing [live logs in the console](https://github.com/caprover/caprover/issues/196).  It will be a great help.

Seems to be working mostly OK, except that at the bottom of the log output, I get something along the following lines:

```
rror grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node wa6h47ncpwxcvob5y52zoalb5 is not available, node htazpi5f501ngw0qvz4b90p1i is not available, node 9x478h4s0xgt5c8jjv3y6jrws is not available
```

These node IDs don't seem to correspond to what is from `docker node ls`... or at least sometimes one of them is the same, but others are not.  And that `rror` is exactly how it appears... it is not `Error`... actually the symbol doesn't show properly in this github post in final form... here is a screenshot:

![image](https://user-images.githubusercontent.com/9009792/52398949-aad2d580-2ab2-11e9-92a2-92dfdf0b72e5.png)

It also seems to struggle a bit for one of my apps where the amount of logging is greater (roughly three lines per second).  The log window is quite temperamental... it's not clear if it will ever update again and then it does, and then sometimes it shows only `fetching app log failed...`, and then populates again (but still with the above message at the bottom.

Maybe it's tricky to achieve with a fast-flowing log, but I recall that the log window in heroku is pretty smooth, and copes with large streams of log data coming in.

And often I find that with I press the cross (top right) from the log page to go back to app listing, I will just get the waiting circle... and this remains for any tab I try to navigate to... even logging out doesn't help because I can't log back in... doesn't respond to the Login button.  Have to close the browser tab and open a new one.

**Comment by githubsaturn** [comment]
CapRover just relays logs from Docker. This appears to be a Docker issue:
https://github.com/moby/moby/issues/35011

`fetching app log failed...` is also result of Docker just giving up completely when trying to fetch the logs. You can probably see more details if you look at the logs `docker service logs captain-captain --follow` when this `fetching app log failed...` happens... But it probably doesn't give you any hint on how to resolve the issue.

`�rror` the broken symbol is a side effect of the broken log stream. The headers must have been shifted...


PS:
Someone has suggested to run the following like on the swarm manager (main node)
```
docker swarm ca --rotate
```
Some people are getting positive results after running this, some don't. Regardless, it's a Docker problem, and there is nothing that can be done at our end :/

https://github.com/moby/moby/issues/35011#issuecomment-373024725

**Comment by drmrbrewer** [comment]
> probably see more details if you look at the logs

The only evidence from the logs appears to be the lack of a response code and time (the first entry below seems to relate to an instance where I got `fetching app log failed...`):

    GET /api/v2/user/apps/appData/meteogram/logs - - ms - -
    GET /api/v2/user/apps/appData/meteogram/logs 200 156.277 ms - 595357

The original post in the moby issue you linked to seems to be suggesting that they have a problem when running `docker service logs` from a terminal, i.e. directly.  For me, getting the app logs in that way is fine.  It's only in the CapRover console where I see the `�rror` message.

Running `docker swarm ca --rotate` did not have any effect.

**Comment by githubsaturn** [comment]
> The original post in the moby issue you linked to seems to be suggesting that they have a problem when running `docker service logs` from a terminal, i.e. directly. For me, getting the app logs in that way is fine. It's only in the CapRover console where I see the `�rror` message.

Do you have a reproducible case for this, or it randomly happens?

CapRover literally just calls Docker API to fetch the logs. Unless Docker CLI internally manipulates data before printing it, they should behave the same.

**Comment by drmrbrewer** [comment]
> Do you have a reproducible case for this, or it randomly happens?

Well it happens for all of my apps (and I have a *lot* of apps)... absolutely fine from the CLI, but with the error message in CapRover console.

I'll see if I can produce a simple test app, but it's quite possible it's something peculiar to my particular setup at present.

**Comment by drmrbrewer** [comment]
I deployed a [test app](https://github.com/drmrbrewer/captest) to the same server and initially I didn't get any error message in CapRover for this app.

What I did notice, however, is that when the app completes its output (counting to 500), dumping the count to the logs, and I then redeploy the app so that the count starts again, the logs from the CLI show it restart and start counting again, but the logs in CapRover don't restart and count in the same way... the output would sometimes "twitch" as if it was trying to update, but wasn't... though I think maybe it was starting to output from the top again, overwriting what was there before?

Can't be sure, because after I redeployed maybe three times, back in CapRover I saw the `fetching app log failed...` message, and now I can't get any logs to show again, even logging out and back in, and redeploying the app.

But I haven't seen the `�rror` message yet with this test app... just `fetching app log failed...`

**Comment by drmrbrewer** [comment]
Now I did a Save and Update on the test app, to see what happens when it restarts that way... and I just see the waiting rotating circle symbol, which remains whatever page I try to navigate to.

Have to close the browser tab completely, and log back in with a new browser tab.

Then I Save and Update again... the CLI logs show the count start again, but not in the CapRover console... though eventually something does appear, and it does seem that some of the latest log output is being dumped higher up in the logs window, not following on from the end.

Then I try Save and Update again... eternal circle waiting symbol again.

**Comment by githubsaturn** [comment]
Thanks for the info. I'll re-open and look into this.

**Comment by drmrbrewer** [comment]
And the output in the logs window, as well as seeming to overwrite itself, doesn't end up doing it from the top... not sure what's happening but the log entries seem to be interleaved... check the times and counts in the following (I would expect it to start overwriting from the top and just continue through):

	2019-02-09T18:59:43.660434146Z i is 478
	2019-02-09T18:59:43.760170499Z i is 479
	2019-02-09T18:59:43.864662685Z i is 480
	2019-02-09T18:59:43.964019688Z i is 481
	2019-02-09T19:03:10.325382685Z i is 468
	2019-02-09T19:03:10.424831109Z i is 469
	2019-02-09T19:03:10.525353128Z i is 470
	2019-02-09T19:03:10.626120985Z i is 471
	2019-02-09T19:03:10.726009772Z i is 472
	2019-02-09T19:03:10.826449947Z i is 473
	2019-02-09T19:03:10.926272195Z i is 474
	2019-02-09T19:03:11.025909893Z i is 475
	2019-02-09T19:03:11.128856215Z i is 476
	2019-02-09T19:03:11.229057861Z i is 477
	2019-02-09T19:03:11.329175951Z i is 478
	2019-02-09T19:03:11.429416188Z i is 479
	2019-02-09T19:03:11.528652520Z i is 480
	2019-02-09T19:03:11.629696819Z i is 481
	2019-02-09T19:03:11.730508010Z i is 482
	2019-02-09T19:03:11.831734011Z i is 483
	2019-02-09T19:03:11.931922336Z i is 484
	2019-02-09T19:03:12.032395301Z i is 485
	2019-02-09T19:03:12.136520063Z i is 486
	2019-02-09T19:03:12.233222384Z i is 487
	2019-02-09T19:03:12.332931574Z i is 488
	2019-02-09T19:03:12.432727338Z i is 489
	2019-02-09T19:03:12.533592756Z i is 490
	2019-02-09T19:03:12.634397852Z i is 491
	2019-02-09T19:03:12.735162440Z i is 492
	2019-02-09T19:03:12.835038737Z i is 493
	2019-02-09T19:03:12.934856671Z i is 494
	2019-02-09T19:03:13.034593311Z i is 495
	2019-02-09T19:03:13.135158503Z i is 496
	2019-02-09T19:03:13.234669197Z i is 497
	2019-02-09T19:03:13.335499406Z i is 498
	2019-02-09T19:03:13.435890994Z i is 499
	2019-02-09T19:03:13.537356368Z i is 500
	2019-02-09T19:13:44.165319595Z i is 139
	2019-02-09T19:13:44.268597114Z i is 140
	2019-02-09T19:13:44.369382802Z i is 141

**Comment by drmrbrewer** [comment]
Let me know if any other info would be helpful... am happy to performing further testing if you guide me in the right direction...

**Comment by githubsaturn** [comment]
Do you happen to run your test on a cluster? Or a single node?

If you're running on a cluster, can you try reproducing this on a single node?

**Comment by githubsaturn** [comment]
Okay, so far, I was able to reproduce the flashing issue and interweaving issue. It's a Docker problem. I'll have to open a new issue with them.

The problem is that the logs that they return is not guaranteed to be sorted based on time. The reason that the `docker service logs` works fine is that it pipes the output to console once it fetches the first batch. However, for CapRover, with every refresh we have to fetch a new set.

In fact, with `docker service logs`  the same issue can be seen if you run `docker service logs myservice --since 5m`  a few time. With every run, the output is different. 

We can "patch" this on the frontend and sort the log values, get rid of dups and etc. But I'd rather first confirm with Docker people to see if they want to fix this or not.



Having said that, I cannot reproduce  `fetching app log failed` ,  `�rror` and the never-ending loading spinner.


It might be useful if you could capture CapRover logs by `docker service logs captain-captain --since 5m` when any of these issues happen.

**Comment by githubsaturn** [comment]
Keep in mind that one of the changes in CapRover is reducing downtime between deploys. To support this, some changes was made to the "update" service procedure which makes it slower. e.g., when you deploy a new image, it may take 30 sec or even more until you see the updated version of your app live. However, this change reduced the "502" error window to a very short time between deploys, so it was a positive change.

This change might also be the result of "eternal loading". In fact, it is most probably not eternal, but in rare cases, it may take up to 1min, even 2 min, to finish.

**Comment by githubsaturn** [comment]
Finally, I was able to reproduce the `Error grabbing logs: rpc error:...` problem as well.

And of course, it's coming from Docker. The reason that you're probably not seeing it is that you attach your terminal to log instead of taking a snapshot of logs (what CapRover needs to do in order to pass the data).

If you simply run `docker service logs srv-captain--myappwhatever --tail 500` you'll see the exact error message. 

I've added some sorting to the next version of CapRover, that should fix the flashing and interweaving issue. For `Error grabbing logs: rpc error`, there is absolutely nothing that can be done This is the output from  `docker service logs srv-captain--test-loggin --tail 500`:
```
srv-captain--test-loggin.1.ub4ff2qqesj8@cluster-2    | i is 497
srv-captain--test-loggin.1.ekgfj749wapv@cluster-2    | i is 498
srv-captain--test-loggin.1.ekgfj749wapv@cluster-2    | i is 499
srv-captain--test-loggin.1.ub4ff2qqesj8@cluster-2    | i is 500
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node ssrfl7j53iguk7f8160457wt2 is not available
```

PS: the broken character was also due to a header that wasn't documented in Docker API, but apparent can happen in the wild. I've added the header and the issue should be gone now.


Next release will include both sorting and the broken character issue. However, as I mentioned, `Error grabbing logs: rpc error` is a legit output of Docker API and will be visible if you run `docker service logs srv-captain--test-loggin --tail 500`  as well.

**Comment by drmrbrewer** [comment]
> if you run `docker service logs myservice --since 5m` a few time. With every run, the output is different.

Yes I do notice this.  However, I always use it with `--follow` and although I suppose that there is still no guarantee of ordering, with a relatively low rate of new log entries they will most likely be showing in time order.

> If you simply run `docker service logs srv-captain--myappwhatever --tail 500` you'll see the exact error message.

Aha, yes that is indeed the case.  But interestingly, as I mentioned just above, I always use it with `--follow` and when you include that option the error message is *not* displayed.  For example, try the following:

    docker service logs srv-captain--myapp --since 0m --follow --timestamps --raw

Is there a way in which you could somehow take the output of the above for use in the CapRover console?  Probably not.

**Comment by drmrbrewer** [comment]
> this change might also be the result of "eternal loading"

maybe, though it shouldn't make the whole CapRover console (all elements, pages) unresponsive?  I'll see if I can work out a pattern as to when this happens, and if it is indeed eternal or just longer than I expected.

**Comment by githubsaturn** [comment]
FTR: this turned out to be a Docker bug: https://github.com/moby/moby/issues/38640

**Comment by skyyy777** [comment]
Well, this is still an issue for me in 2021. Any news on this topic? Sometimes it works, sometimes not.

**Comment by githubsaturn** [comment]
Unfortunately this is a Docker issue. There is nothing that we can do on CapRover side to mitigate this issue. Relevant issues on Docker:
https://github.com/moby/moby/issues/35011
https://github.com/moby/moby/issues/38640
https://github.com/moby/moby/issues/41733

Potential solutions that "may" help:
- Run `docker swarm ca --rotate` on your main node
- Reboot your machines

**Comment by JeFawk** [comment]
Having this issue a lot with a single node, supposedly docker fixed it in https://github.com/moby/moby/pull/39360 but I'm still getting a lot of `fetching app log failed...`

Any ideas what I could try? Thanks!

**Comment by abhranil26** [comment]
i have now defaulted to using [dozzle](https://github.com/amir20/dozzle) for viewing my docker logs

**Comment by drmrbrewer** [comment]
Looks like dozzle is already available in CapRover as a [one-click app](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/dozzle.yml)... latest version of dozzle (`pr-3124`) seems to work fine.  Thanks for the suggestion.
