### ISSUE TITLE
Feature Request] Container Consolse in App Page

### ISSUE THREAD

**Issue by hamza-younas94** [caprover/caprover#398]
Each and everything in Apps page we can deploy with different methods but sometime we have to run some specific command in container then need to do ssh the server and access the container to run the command, if it is possible console is showing in specific Apps page and where we run commands in container

**Comment by JacobSamro** [comment]
It think [portainer](https://github.com/portainer/portainer) has this option. May be you can take some inputs there.

**Comment by githubsaturn** [comment]
@hamza-younas94  , Can you please point out a few use cases for this feature? Are these one-off commands?

As long as it doesn't require an interactive shell, it is doable. For an interactive shell, we need to do a significant refactoring of our http API.

**Comment by hamza-younas94** [comment]
@githubsaturn  in some case need to run some command like in laravel i have php artisan commands for generating controllers, models etc then i have to ssh the main server then ssh the container to run the commands, yes it is doable because then i dont have to ssh the server

**Comment by amanvishnani** [comment]
I have deployed Portainer on my CaptainRover but unable to attach the shell to the containers.
I get a timeout error. Anyone else facing this issue?

**Comment by atominvention** [comment]
@amanvishnani I face it too, we should modify nginx config to support the web socket as mentioned in the doc
[https://portainer.readthedocs.io/en/latest/faq.html#how-can-i-configure-my-reverse-proxy-to-serve-portainer](url)

but I have no luck getting it to work

**Comment by MeXaaR** [comment]
toggle "websocket support" and it should work.

**Comment by timitimitimi** [comment]
I'm confused, my apps have websocket support enabled and yet it still hangs on new console or attach ?
