### ISSUE TITLE
dhparams file is empty

### ISSUE THREAD

**Issue by githubsaturn** [caprover/caprover#745]
Creating this issue as it was reported by a user on Slack. After upgrading to 1.7, the nginx broke due to a faulty dhparam file. If you face this issue simply remove the file and restart your CapRover:

```
rm /captain/data/nginx-shared/dhparam.pem
docker service update captain-captain --force
```

**Comment by githubsaturn** [comment]
Properly fixed in https://github.com/caprover/caprover/commit/ed3aa9e4650439e57352c9718a6252c4adf0b0b0

Now we remove the file if it's empty automatically.

**Comment by Smerity** [comment]
I just upgraded to 1.7.1 from the in-app update suggestion of 1.6.0 or 1.6.1 and ran across this issue. After looking at the logs and realizing it was an `nginx` and `dhparams` related problem, then finding this issue, I was able to solve it by running the command above.

This may suggest the issue can still occur? I'd attach the logs but it appears they disappeared on restarting the container. I don't have them in my terminal scrollback. I'm happy to provide any additional details that might help suggest why it re-occurred in my situation.

**Comment by githubsaturn** [comment]
The fix is [not part of 1.7.1](https://github.com/caprover/caprover/blob/master/CHANGELOG.md#next-version---available-as-edge). It was reported after the release. I didn't cut a hotfix as I thought it's not happening that often. 

We might end up having to cut a hotfix if it's not really a corner case.

**Comment by Smerity** [comment]
Ah, I misunderstood and incorrectly thought the fix had made it into 1.7.1. Thanks for pointing me to the changelog!

Thanks for the response and I love CapRover - supporting it via OpenCollective =]

**Comment by githubsaturn** [comment]
Thanks! And more importantly, I've also seen your support on HN too! It's appreciated!
